import{createClient}from"https://esm.sh/@supabase/supabase-js@2";import{encryptValue,hashValue,importKey}from"../_shared/crypto.ts";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const J=(b:Record<string,unknown>,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...H,"Content-Type":"application/json"}});
const req=(v:unknown,n:string,m:number)=>{const r=String(v??"").trim();if(!r)throw new Error(`${n} is required`);if(r.length>m)throw new Error(`${n} is too long`);return r};
const opt=(v:unknown,m:number)=>{const r=String(v??"").trim();return r?r.slice(0,m):null};
const digs=(v:unknown,a:number,b:number,n:string)=>{const r=String(v??"").replace(/\D/g,"");if(r.length<a||r.length>b)throw new Error(`${n} has an invalid length`);return r};
Deno.serve(async q=>{if(q.method==="OPTIONS")return new Response("ok",{headers:H});if(q.method!=="POST")return J({error:"Method not allowed"},405);try{
const u=Deno.env.get("SUPABASE_URL"),sr=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),ek=Deno.env.get("INTAKE_ENCRYPTION_KEY"),salt=Deno.env.get("INTAKE_RATE_LIMIT_SALT"),kv=Deno.env.get("INTAKE_ENCRYPTION_KEY_VERSION")||"v1";if(!u||!sr||!ek||!salt)return J({error:"Server configuration incomplete"},500);
const b=await q.json();if(b.consent!==true)return J({error:"Consent required"},400);const routing=digs(b.routing_number,9,9,"Routing number"),account=digs(b.account_number,4,20,"Account number"),license=req(b.drivers_license_number,"Driver license number",40);
const ip=(q.headers.get("x-forwarded-for")||q.headers.get("cf-connecting-ip")||"unknown").split(",")[0].trim(),iph=await hashValue(`${ip}:${salt}`),admin=createClient(u,sr,{auth:{persistSession:false,autoRefreshToken:false}}),since=new Date(Date.now()-3600000).toISOString();
const{count,error:ce}=await admin.from("intake_submission_limits").select("*",{count:"exact",head:true}).eq("ip_hash",iph).gte("submitted_at",since);if(ce)throw ce;if((count||0)>=10)return J({error:"Too many submissions"},429);
const key=await importKey(ek),[el,er,ea]=await Promise.all([encryptValue(key,license),encryptValue(key,routing),encryptValue(key,account)]),days=Number(Deno.env.get("INTAKE_SENSITIVE_RETENTION_DAYS")||"90"),ret=new Date(Date.now()+days*86400000).toISOString().slice(0,10);
const intake={first_name:req(b.first_name,"First name",80),middle_name:opt(b.middle_name,80),last_name:req(b.last_name,"Last name",80),date_of_birth:opt(b.date_of_birth,10),business_name:opt(b.business_name,160),client_type:req(b.client_type,"Client type",30),email:req(b.email,"Email",254),phone:req(b.phone,"Phone",20),preferred_contact_method:req(b.preferred_contact_method,"Preferred contact",20),address_line_1:req(b.address_line_1,"Address",160),address_line_2:opt(b.address_line_2,120),city:req(b.city,"City",100),state:req(b.state,"State",2).toUpperCase(),postal_code:req(b.postal_code,"ZIP",10),drivers_license_state:opt(b.drivers_license_state,2)?.toUpperCase(),drivers_license_expiration:opt(b.drivers_license_expiration,10),drivers_license_number:license,direct_deposit_requested:b.direct_deposit_requested===true,bank_name:opt(b.bank_name,120),bank_account_type:opt(b.bank_account_type,20),routing_number:routing,account_number:account};
const{data,error}=await admin.rpc("create_sensitive_walk_in_intake",{p_intake:intake,p_encrypted_drivers_license:el.ciphertext,p_drivers_license_iv:el.iv,p_encrypted_routing_number:er.ciphertext,p_routing_number_iv:er.iv,p_encrypted_account_number:ea.ciphertext,p_account_number_iv:ea.iv,p_key_version:kv,p_retention_delete_after:ret});if(error)throw error;await admin.from("intake_submission_limits").insert({ip_hash:iph});return J({confirmation_code:data.confirmation_code});
}catch(e){console.error("Sensitive intake submission failed");return J({error:e instanceof Error?e.message:"Rejected"},400)}});
